#!/bin/bash 

#=======================================================================
#
# arxiv-get <id>
#
# Given an arXiv ID number (eg. 1502.06853, hep-ph/9910388, etc.) this
# script will gather the article metadata. It will then output the
# metadata to the console and attempt to copy it to the user's clipboard
# using 'xclip'; it will also output a message as to whether this was
# successful.
#
#=======================================================================

#----------------------------------------------------------
# Functions 
#----------------------------------------------------------

# prints some usage instructions
function Usage {
Usage=" Usage: arxiv-get <id>"
echo $Usage;
printf '\n'; echo "Example usage:"; echo "arxiv-get 0908.1780";
echo "arxiv-get gr-qc/9603051";
echo
}

#----------------------------------------------------------
# Error Checking
#----------------------------------------------------------

case $# in
  1) ;; # continue as normal
  *) Usage; exit 1 ;;
esac

#----------------------------------------------------------
# Main Program
#----------------------------------------------------------

# attempt to download the article metadata
cd /tmp
wget -O metadata.tmp --user-agent="Mozilla" https://arxiv.org/abs/$1 > /dev/null 2>&1
if [ $? -ne 0 ]
  then
    echo "arXiv ID not found or connection error. Exiting."
    exit 1
fi

# from the metadata file, retrieve the useful information
title=`cat metadata.tmp | grep citation_title | cut -c40- | sed 's/...$//'`
num_authors=`cat metadata.tmp | grep citation_author | wc -l`
author=`cat metadata.tmp | grep -m1 citation_author | cut -c41- | sed 's/...$//'`
doi=`cat metadata.tmp | grep citation_doi | cut -c37- | cut -d'"' -f2`
year=`cat metadata.tmp | grep citation_date | cut -c39- | sed 's/.........$//'`
id=`cat metadata.tmp | grep citation_pdf_url | cut -c64- | sed 's/...$//'`
url="https://arxiv.org/abs/${id}"

# do some post-processing
if [ $num_authors -ne 1 ]
then
  author="${author} et al."
fi
author_short=`echo $author | awk '{print $1;}' | sed 's/.$//' | awk '{print tolower($0)}'`
id_short=`echo "$1" | sed -r 's/[a-z]//g' | sed -r 's/-//g' | sed -r 's|/||g'`
doi="https://dx.doi.org/$doi"

# print to terminal window
printf "\n"
echo "[$author_short$year-$id_short]
$title
$author ($year)
$url
$doi"
printf "\n\n"

# attempt to copy the text using xclip
printf "[$author_short$year-$id_short]\n$title\n$author ($year)\n$url\n$doi" | xclip -sel c
if [ $? -eq 0 ] 
then  # it is installed
  printf "\n\e[1A\e[01;42m COPY TO CLIPBOARD SUCCESSFUL\e[0m\n"
else  # it is not installed
  printf "\e[1A\e[01;41m COPY TO CLIPBOARD FAILED \e[0m\n"
fi

# clean up
rm /tmp/metadata.tmp
